# -*- coding: utf-8 -*-
"""Test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15wkm9zKV2_FOCYVZJIo2Zz2DOrj6Yfb1
"""

import pandas as pd

dataset = pd.read_csv('cancer.csv')

x = dataset.drop(columns=["diagnosis(1=m, 0=b)"])

y = dataset["diagnosis(1=m, 0=b)"]

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

# Convert to NumPy arrays for compatibility with TensorFlow
x_train = x_train.values
x_test = x_test.values
y_train = y_train.values
y_test = y_test.values

import tensorflow as tf

model = tf.keras.models.Sequential([
    tf.keras.Input(shape=(x_train.shape[1],)), # Define the input shape for the model
    tf.keras.layers.Dense(256, activation='sigmoid'),
    tf.keras.layers.Dense(256, activation='sigmoid'),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

model.summary() # Add this line to inspect the model's structure

# Model layers are now defined in the Sequential constructor, this cell can be empty or removed.

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

model.fit(x_train, y_train, epochs=10000)

model.evaluate(x_test, y_test)